"""Run an arbitrary ``@``-tokened template string through
``caldanai.lib.rpg.helpers.parser.parse`` with stubbed actors,
printing the rendered result.

Built so we can rapidly iterate on narrative templates (especially
ones generated by external narrators — e.g. a future Claude-API-
based narrator) without having to wire up a full ``Creature`` /
``Player`` in a test fixture. Minimal ``SimpleNamespace`` stubs
cover everything :func:`parse` accesses on actors.

Usage::

    python -m tools.parse_template \
        --actor "Caels:player:male" \
        --actor "bandit:monster:female" \
        --template "@1 swings at @2d."

    python -m tools.parse_template \
        --actor "Caels:player:male" \
        --actor "bandit:monster:female" \
        --template-file sonnet_output.txt

    cat sonnet_output.txt | python -m tools.parse_template \
        --actor "Caels:player:male" \
        --actor "bandit:monster:female"

Actor spec format: ``NAME:KIND:GENDER[:MENTION]``

- ``NAME``: actor name as the parser will see it (e.g. ``Caels``,
  ``bandit``).
- ``KIND``: ``player`` (``uses_article=False``, bare ``@1``
  renders as the name) or ``monster`` (``uses_article=True``,
  bare ``@1`` renders as the name with no article, ``@1d``
  prepends ``the``).
- ``GENDER``: ``male`` / ``female`` / ``nonbinary`` / ``neuter``.
  Maps to the same pronoun sets ``Creature`` uses.
- ``MENTION`` (optional, 4th field): Discord mention string like
  ``<@!111111111111111111>``. When present, populates a
  ``member.mention`` attribute on the actor stub so the parser's
  ``@Nm`` mention form resolves to it. Omit for monsters / NPCs
  and for players whose mention isn't being tested.

Why this exists: inline ``python -c`` loops that set up actors and
call ``parse()`` used to force per-call permission approvals and
drifted each rewrite. This module replaces them with a stable
entrypoint.
"""

from __future__ import annotations

import argparse
import sys
from types import SimpleNamespace
from typing import Dict, List, Optional

from caldanai.lib.rpg.helpers.enums import Pronouns
from caldanai.lib.rpg.helpers.parser import PLURAL_VERB_SUBJECTIVES, parse


# Mirrors ``Creature._populate_pronouns`` — kept here so stubs don't
# need a real Creature instance, and drift between the two is caught
# by a unit test.
_PRONOUN_SETS: Dict[str, Dict[Pronouns, str]] = {
    "male": {
        Pronouns.SUBJECTIVE: "he",
        Pronouns.OBJECTIVE:  "him",
        Pronouns.POSSESSIVE: "his",
        Pronouns.ADJECTIVE:  "his",
        Pronouns.REFLEXIVE:  "himself",
    },
    "female": {
        Pronouns.SUBJECTIVE: "she",
        Pronouns.OBJECTIVE:  "her",
        Pronouns.POSSESSIVE: "hers",
        Pronouns.ADJECTIVE:  "her",
        Pronouns.REFLEXIVE:  "herself",
    },
    "nonbinary": {
        Pronouns.SUBJECTIVE: "they",
        Pronouns.OBJECTIVE:  "them",
        Pronouns.POSSESSIVE: "theirs",
        Pronouns.ADJECTIVE:  "their",
        Pronouns.REFLEXIVE:  "themself",
    },
    "neuter": {
        Pronouns.SUBJECTIVE: "it",
        Pronouns.OBJECTIVE:  "it",
        Pronouns.POSSESSIVE: "its",
        Pronouns.ADJECTIVE:  "its",
        Pronouns.REFLEXIVE:  "itself",
    },
}


def _make_actor(spec: str) -> SimpleNamespace:
    parts = spec.split(":")
    if len(parts) not in (3, 4):
        raise SystemExit(
            f"bad --actor spec {spec!r}: expected NAME:KIND:GENDER[:MENTION]"
        )
    name, kind, gender = parts[:3]
    mention = parts[3] if len(parts) == 4 else None
    kind = kind.lower()
    gender = gender.lower()
    if kind not in ("player", "monster"):
        raise SystemExit(
            f"bad --actor kind {kind!r}: must be 'player' or 'monster'"
        )
    if gender not in _PRONOUN_SETS:
        raise SystemExit(
            f"bad --actor gender {gender!r}: "
            f"must be one of {sorted(_PRONOUN_SETS)}"
        )
    pronouns = _PRONOUN_SETS[gender]
    actor = SimpleNamespace(
        name=name,
        uses_article=(kind == "monster"),
        gender=gender,
        pronouns=pronouns,
        plural_verbs=(
            pronouns[Pronouns.SUBJECTIVE].lower() in PLURAL_VERB_SUBJECTIVES
        ),
    )
    if mention:
        actor.member = SimpleNamespace(mention=mention)
    return actor


def _read_template(args: argparse.Namespace) -> str:
    if args.template is not None:
        return args.template
    if args.template_file is not None:
        with open(args.template_file, "r", encoding="utf-8") as f:
            return f.read()
    return sys.stdin.read()


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__.split("\n\n")[0]
    )
    ap.add_argument(
        "--actor", action="append", default=[], required=True,
        help="Actor spec NAME:KIND:GENDER (repeat for @2, @3, ...)",
    )
    grp = ap.add_mutually_exclusive_group()
    grp.add_argument("--template", help="Template string (inline)")
    grp.add_argument(
        "--template-file",
        help="Path to UTF-8 file containing the template. "
             "Omit both --template and --template-file to read from stdin.",
    )
    args = ap.parse_args(argv)

    actors = [_make_actor(s) for s in args.actor]
    template = _read_template(args)
    rendered = parse(template, *actors)
    print(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
